{PROGRAMA QUE DEMUESTRA QUE PASCAL NO TIENE UN SISTEMA DE TIPOS SEGURO}
{SISTEMA DE TIPOS SEGURO: SI EN EL CHEQUEO DE TIPOS SE PUEDE DETERMINAR QUE NO SE REALIZAN OPERACIONES INVALIDAS}
program ej7;

var 
	arr : ARRAY [1..1] of String;
	y : Integer;

begin
  y:=2;
  arr[2] := 'UN STRING';
  writeln(arr[2]);
end.