// Class automatically generated by Dev-C++ New Class wizard
    
#include <iostream.h>
    
class ListaSobreArreglo
{
      public:
             //esto no funca#define MAX 100;
	     static const int MAX = 100;
             int items[];
             int numItems;
              
      ListaSobreArreglo(void){
             items[100];
             numItems = 0;   
      }
      
      bool esVacia(void){
           return (numItems == 0);
      }
      
      int longitud(void){
          return (numItems);
      }
      
      void vaciar(void){
           numItems = 0;
      }
      
      void insertar(int index, int item){
           if (numItems == MAX){
                        cout << "Lista llena \n" ;
           }else{
                 if ((index <= 0) || (index > numItems +1)){
                            cout << "Indice invalido \n";
                 }else{
		 	
                       if (index == numItems+1){
                                 items[index-1] = item;
				 cout << item << "veamos que paso" << items[index-1] << " \n";
                                 numItems++;
				 cout << item << "veamos que paso" << items[index-1] << " \n";
				 /**
				 *
				 * Chino el problema de esto esta despues que 
				 * incremento numItems. No se por que me cambia 
				 * el valor de lo que inserte en el arreglo
				 *
				 **/
				 
                       }else{
                             int temp = items[index-1];
                             items[index-1] = item;
                             insertar(index+1, temp);
                       }
                 }
           }
	   
      }

      void eliminar(int index){
           if ((index <= 0) || (index > numItems)){
                        cout << "Indice invalido \n" ;
           }else{
                 if (index == numItems){
                           numItems--;
                 }else{
                       items[index-1] = items[index];
                       eliminar(index+1);
                 }
                 
           }
      }
      
      int obtener(int index){
          if ((index <= 0) || (index > numItems)){
                    cout << "Indice invalido \n";
          }else{
	  	
                return (items[index-1]);
          }
      }
      
};
    
int main (void)
{
    ListaSobreArreglo lista;
    lista.insertar(1, 3);
    cout << lista.obtener(1) << " obtener \n";

    return 0;
}
